config/routes.rb
Rails.application.routes.draw do
  get 'search/animals'

  devise_for :users
  resources :facilities do
    resources :animals
  end
  resources :users, :only => [:index, :show]

  resources :animals, only: [:show]


  namespace :settings do
    get '/', to: 'settings#list'
    resources :species, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :sexes, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :rearings, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :reproductive_statuses, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :facility_types, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :facility_expertises, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end

  end
  

  root 'page#index'
end

app/models/facility.rb
class Facility < ApplicationRecord
  has_many :animals
  has_many :facilities_users
  has_many :users, through: :facilities_users
  has_many :pictures, :dependent => :destroy
  belongs_to :facility_type
  
  accepts_nested_attributes_for :facilities_users

  validates :name, presence: true
  validates :facility_type_id, presence: true

  accepts_nested_attributes_for :pictures

  geocoded_by :address
  after_validation :geocode
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  after_validation :geocode, if: ->(facility){ facility.address.present? && facility.address_changed? }

  VALID_INTERESTS = {
    'grow_herd_size'                  => 'Interested in breeding to grow herd size',
    'maintain_herd_size'              => 'Interested in breeding to maintain herd size',
    'decrease_herd_size'              => 'Interested in decreasing herd size',
    'house_post_reproductive_animals' => 'Interested in housing post-reproductive animals',
    'house_new_species'               => 'Interested in housing new species'
  }.freeze

  before_save { |facility| facility.interests = facility.interests.uniq.select{ |e| VALID_INTERESTS.keys.include?(e) }  }

  VALID_INTERESTS.keys.each do |interest|
    define_method("interest_to_#{interest}?"){ interests.include?(interest) }
  end
end

app/models/facility_type.rb
class FacilityType < Setting
  has_many :facilities
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility_user
  before_action :set_facility, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Facility.all
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
    @facility.facilities_users.build
    @facility.pictures.build
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      if current_user.site_admin? || action_name == 'show'
        @facility = Facility.find(params[:id])
      else # restrict edit/update/destroy to only facilities associated with the user.
        begin
          @facility = current_user.facilities.find(params[:id])
        rescue
          render_not_found('Sorry, that facility could not be found.')
        end
      end
    end

    def set_facility_user
      @facility_user = FacilityUser.find_by(user_id: current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(
        :name,
        :approved,
        :facility_type_id,
        :spa,
        :acreage,
        :endangered_acreage,
        :temperture_controled,
        :water_features,
        :supplemental_feed,
        expertise: [],
        interests: [],
        pictures_attributes: [:name, :image],
        facilities_users_attributes: [:user_id, :facility_id]
      )
    end
end

app/views/facilities/_form.html.erb
<%= simple_form_for(@facility, multipart: true) do |f| %>
  <%= f.error_notification %>
  <%= f.simple_fields_for :facilities_users do |fu| %>
  	<%= fu.input :user_id, input_html: { value: current_user.id }, :as => :hidden %>
  <% end %>
  <%= f.input :name %>
  <%= f.input :facility_type_id,  as: :radio_buttons, collection: FacilityType.all %>
  <div class="form-group check_boxes optional facility_interests">
    <%= f.simple_fields_for :pictures do |p| %>
      <%= p.label :image %>
      <%= p.file_field :image %>
    <% end %>
  </div>


  <%= f.input :interests, as: :check_boxes, collection: Facility::VALID_INTERESTS.to_a.map(&:reverse) %>

  <%= f.input :expertise, as: :check_boxes, collection: FacilityExpertise.all.map{|f| [f.name, f.id.to_s]} %>
  <%= f.input :spa %>
  <%= f.input :acreage %>
  <%= f.input :endangered_acreage, label: 'Total acreage utilized for endangered species management' %>
  <%= f.input :temperture_controled %>
  <%= f.input :water_features %>
  <%= f.input :supplemental_feed %>
  <%= f.button :submit %>
<% end %>

app/views/facilities/edit.html.erb
<h1>Editing Facility</h1>

<%= render 'form' %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.erb
<h1>Facilities</h1>
<br />
<%= chart(:Map, [['Lat', 'Long', 'Name']]+Facility.all.map{ |e| [e.latitude, e.longitude, e.name] }, map_chart_styles) if Facility.any? %>
<br /><br />
<%= link_to 'Add New Facility', new_facility_path, class: 'btn btn-primary' %>
<br /><br />
<div class="row">
  <% @facilities.each do |facility| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail"> 
        <%= image_tag facility.pictures.first.image.url(:portfolio_large), class: "static-image img-responsive" if facility.pictures.first.present? %>
        <div class="caption">
          <h3><%= facility.name %></h3>
          <p>This facility has <%= facility.animals.count %> animals.</p>
            <%= link_to 'Show', facility, class: 'btn btn-primary' %>
            <% if current_user.try :site_admin? %>
            <%= link_to 'Edit', edit_facility_path(facility), class: 'btn btn-default' %>
            <%= link_to 'Delete', facility, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/facilities/new.html.erb
<h1>New Facility</h1>

<%= render 'form' %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <%= @facility.name %>
    </h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <%= image_tag @facility.pictures.first.image.url(:large) if @facility.pictures.first %>
  </div>

  <div class="col-md-4">
    <p>
      <% if current_user.try :site_admin? %>
        <%= link_to 'Edit', edit_facility_path(@facility), class: 'btn btn-default' %>
      <% end %>
      <br />
      <br/>
      <%= link_to 'Back', facilities_path, class: 'btn btn-default' %>
      <br />
      <br/>
     
    </p>
  </div>
</div>
<hr />
<div class="row">
  <div class="col-lg-12">
    <h2>Animals</h2>
     <%= link_to 'Add Animal', new_facility_animal_path(facility_id: @facility.id), class: 'btn btn-primary' %>
  </div>
  </div>
  <br />
  <div class="row">
    <%= render @facility.animals %>
  </div>


<div class="row">
  <div class="col-lg-6">
    <%= chart(:PieChart, [['Gender', 'Total']]+@facility.animals.reduce(Hash.new(0)){ |s, e| s[e.gender] += 1; s}.to_a ) %>
  </div>
  <div class="col-lg-6">
    <%= chart(:PieChart, [['Species', 'Total']]+@facility.animals.reduce(Hash.new(0)){ |s, e| s[e.species.name] += 1; s}.to_a ) %>
  </div>
  <div class="col-lg-12">
    <%= chart(:Histogram, [['Animal', 'Age']]+@facility.animals.map{ |e| [e.name, e.age]}, title: "Age distribution") %>
  </div>

    <%
    # TODO: geo chart still has fake data
    #chart(:GeoChart, [['State', 'Animals'],['US-IL', 2], ['US-IN', 5],['US-IA', 1],['US-TX', 2], ['US-CA', 7],['US-VA', 6]], region: "US", resolution: "provinces")
    %>

  </div>
</div>