config/routes.rb
Rails.application.routes.draw do
  get 'search/animals'

  devise_for :users
  resources :facilities do
    resources :animals
  end
  resources :users, :only => [:index, :show]

  resources :animals, only: [:show]


  namespace :settings do
    get '/', to: 'settings#list'
    resources :species, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :sexes, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :rearings, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :reproductive_statuses, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :facility_types, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :facility_expertises, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end

  end
  

  root 'page#index'
end

app/models/setting.rb
class Setting < ApplicationRecord
  acts_as_list scope: [:type]
  
  #validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :type }
end

app/controllers/settings/settings_controller.rb
class Settings::SettingsController < ApplicationController
  before_filter :find_setting, :except => ['reorder', 'list']

  def list
    @page_title = "Settings"

    render 'settings/list'

  end
  
  def index
    @page_title = @setting.class.to_s.underscore.pluralize.titleize
    @body_id = 'settings'
    @settings = setting.all
    
    respond_to do |format|
      format.html do
        render :template => 'settings/index'
      end
    end
    
  end
  
  def reorder
    params[class_name.singularize].each_with_index do |id, position|
      setting.update_all({position: position + 1},{id: id})
    end
    render :nothing => true
  end
  
  def create
      if @setting.save
        render 'settings/create', layout: false, format: 'js'
      else
        render js: 'alert("Unable to save. Please verify it is not a duplicate.");'
      end
  end
  
  def edit
    render 'settings/edit', layout: false, format: 'js'
  end
  
  def update
    if @setting.update_attributes(params[class_name.singularize])
      render 'settings/update', layout: false, format: 'js'
    end
  end
  
  def destroy
    @setting.destroy
    render js: "$jq('##{dom_id(@setting)}').remove();"
  end
  
  def clone_ranks
    master_ranks_program_id = "0"
    @program = @setting
    @cloned_program = @school.programs.find(params[:cloned_program_id]) rescue nil

    flash[:notice] = "Unable to find program to copy ranks."
    unless @cloned_program.blank? && params[:cloned_program_id] != master_ranks_program_id
      flash[:notice] = "Unable to copy ranks."
      if @program.clone_ranks(@school, @cloned_program)
        flash[:notice] = nil
      end
    end
    redirect_to settings_program_ranks_path(@program)
  end
  
  private

  def find_setting
    @setting = case params[:action]
               when 'index' then setting.new
               when 'create' then setting.new(params[class_name.singularize])
               else setting.find(params[:id]) 
               end
    
    @setting
  end

  def setting
    class_name.singularize.titleize.gsub(/\s/,'').constantize    
  end
  
  def class_name
    uri_array = request.url.split('/')
    settings_index = uri_array.index('settings')
    return uri_array.at(settings_index.next)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
  def to_underscore(setting)
    setting.class.to_s.underscore.pluralize.downcase
  end
  
  def to_title(setting)
    setting.class.to_s.titleize
  end
end

app/views/settings/_setting.html.erb
<li id="<%= dom_id(setting) %>" class="list-group-item">
  <table>
    <tr>
      <th class="handle" style="width: 260px">
        <%= setting.name %>
      </th>
      <td>
      <%= link_to 'Rename', "/settings/#{to_underscore(setting)}/#{setting.id}/edit", remote: true, class: 'danger' %>
      <%= link_to 'Delete', "/settings/#{to_underscore(setting)}/#{setting.id}", remote: true, method: :delete, confirm: 'Are you sure? Any records associated with this setting will no longer have this setting.', class: 'danger' %>
      </span>
      </td>
    </tr>
  </table>
</li>

app/views/settings/index.html.erb
<h2><%= @page_title %></h2>

<well class="info" id="setting_info">
  <strong>
    Add, rename, reorder, or delete
    <%= to_title(@setting).pluralize.downcase %>
  </strong>
  <br/>
  <p>
  <%= %Q(Changes to settings are reflected globally. For example, if you change "Species" to "species", any instance of "Species" will be replaced with "species." You can reorder settings by dragging the name up or down.).gsub('settings', to_title(@setting).pluralize.downcase) %>
  </p>
</well>
<div class="categories">
  <ul class="list-group sortable-list" data-sort-url="/settings/<%= to_underscore(@setting) %>/reorder" id="setting_list">
    <%= render :partial => 'settings/setting', :collection => @settings %>
  </ul>
  <%= form_for([:settings, @setting], :loading => "Form.Element.disable('new_submit').value='Adding #{to_title(@setting)}...'", :complete => "Form.Element.enable('new_submit').value='Add #{to_title(@setting)}'", :html => {:id => 'setting_form'}, :remote => true) do |r| %>
    <div style="margin-top: 10px">
      <%= r.text_field :name, :size => 30 %>
      <%= submit_tag "Add #{to_title(@setting)}", :id => 'new_submit' %>
    </div>
  <% end %>
</div>

app/views/settings/list.html.erb
<h2><%= @page_title %></h2>
<h5>The following setting types are available. Changes made to settings are reflected globally.</h5>
<ul>
  <li><%= link_to 'Species', settings_species_index_path %></li>
  <li><%= link_to 'Facility Types', settings_facility_types_path %></li>
  <li><%= link_to 'Facility Expertises', settings_facility_expertises_path %></li>
  <li><%= link_to 'Rearings', settings_rearings_path %></li>
  <li><%= link_to 'Reproductive Statuses', settings_reproductive_statuses_path %></li>
  <li><%= link_to 'Sexes', settings_sexes_path %></li>
  
</ul>