config/routes.rb
Rails.application.routes.draw do
  get 'search/animals'

  devise_for :users
  resources :facilities do
    resources :animals
  end
  resources :users, :only => [:index, :show]

  resources :animals, only: [:show]


  namespace :settings do
    get '/', to: 'settings#list'
    resources :species, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :sexes, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :rearings, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :reproductive_statuses, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :facility_types, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :facility_expertises, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end

  end
  

  root 'page#index'
end

app/models/animal.rb
class Animal < ApplicationRecord
  include Searchable

  Animal.search_endpoint = ENV['CLOUDSEARCH_ANIMALS_SEARCH_URL']
  Animal.doc_endpoint = ENV['CLOUDSEARCH_ANIMALS_DOC_URL']

  belongs_to :facility
  belongs_to :species
  belongs_to :sex
  belongs_to :rearing
  belongs_to :reproductive_status

  has_many :pictures, :dependent => :destroy

  validates :name, presence: true
  validates :facility_id, presence: true
  validates :species_id, presence: true
  validates :date_of_birth, presence: true

  scope :searchable, -> { where(searchable: true) }

  VALID_INTERESTS = ["keep", "sell", "trade", "loan", "sell or trade in 1-2 years", "looking for mate"].freeze
  
  before_save { |animal| animal.interests = animal.interests.uniq.select{ |e| VALID_INTERESTS.include?(e) } }

  accepts_nested_attributes_for :pictures

  def age
    return unless date_of_birth.present?
    ((Time.now - date_of_birth.to_time) / 1.year).round
  end

  def gender
    sex.try :name
  end

  VALID_INTERESTS.each do |interest|
    define_method("interest_to_#{interest}?"){ interests.include?(interest) }
  end

  private

  def ngrams
    name.split(' ').tap do |ngrams|
      ngrams << date_of_birth.year if date_of_birth.present?
      ngrams << sex.name if sex.present?
      ngrams << rearing.name if rearing.present?
      ngrams << reproductive_status.name if reproductive_status.present?
      ngrams << studbook if studbook.present?
      ngrams << tag if tag.present?
      ngrams << transponder if transponder.present?
    end
  end

  def indexed_fields
    {
      date_of_birth: date_of_birth.present? ? date_of_birth.strftime('%FT%TZ') : nil,
      species: species.name.downcase,
      facility: facility.name.downcase,
      ngrams: ngrams
    }
  end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]
  before_action :set_facility, except: [:search,:show]
  before_action :authenticate_user!, except: [:show]

  # GET /animals
  # GET /animals.json
  def index
    @animals = @facility.animals.all unless @facility.nil?
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    nearby = @animal.facility.nearbys(50000)
    @facility = @animal.facility.id
    @animal_match = AnimalMatch.new
    #worked yesterday, nearby not working today
    #@nearby_animals = Animal.male.where(:facility_id => @animal.facility.nearbys(50000).map(&:id),species_id: 7)
   
    @nearby_animals = if nearby
      Animal.
        where(:facility_id => nearby.map(&:id), species_id: @animal.species_id).
        where("sex_id != #{@animal.sex_id}")
      else
      []
    end
    
  end

  # GET /animals/new
  def new
    
    @animal = Animal.new
    @animal.pictures.build
  end

  # GET /animals/1/edit
  def edit
    @animal.pictures.build
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = @facility.animals.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to facility_animal_path(@facility, @animal) , notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to facility_animal_path(@facility, @animal), notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to facility_animals_path @facility, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    def set_facility
      @facility = Facility.find(params[:facility_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name,
        :species_id,
        :facility_id,
        :date_of_birth,
        :studbook,
        :transponder,
        :sire,
        :dam,
        :tag,
        :comments,
        :searchable,
        :sex_id,
        :rearing_id,
        :reproductive_status_id,
        pictures_attributes: [:name, :image],
        interests: []
        )
    end
end

app/views/animals/_animal.html.erb
<div class="animal col-md-4">
  <div class="thumbnail">
  <%= link_to facility_animal_path(animal.facility, animal) do %>
    <% if animal.pictures.first.present? %>
      <%= image_tag animal.pictures.first.image.url(:large), class: "static-image img-responsive" %>
    <% end %>
  <% end %>
  <div class="caption">
  <h3><%= link_to animal.name, facility_animal_path(animal.facility, animal) %></h3>
  <p>Species: <%= animal.species.name %></p>
  <p>Studbook: <%= animal.studbook %></p>
  <p>Facility: <%= animal.facility.name %></p>
  <p>Birth Date: <%= animal.date_of_birth %></p>
  </div>
  </div>
</div>

app/views/animals/_form.html.erb
<%= simple_form_for([@facility, @animal], multipart: true) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :species_id, collection: Species.all %>
  <%= f.input :sex_id, collection: Sex.all %>
  <%= f.input :rearing_id, collection: Rearing.all %>
  <%= f.input :reproductive_status_id, collection: ReproductiveStatus.all %>
  <%= f.input :date_of_birth, start_year: 1990,
                              end_year: Date.today.year,
                              order: [:month, :day, :year] %>

  <%= f.input :interests, as: :check_boxes, collection: Animal::VALID_INTERESTS %>

  <%= f.input :studbook, label: 'Studbook Number' %>
  <%= f.input :transponder, label: 'Transponder Number' %>
  <%= f.input :sire, label: 'Sire' %>
  <%= f.input :dam, label: 'Dam' %>
  <%= f.input :tag %>
  <%= f.input :searchable %>
  <%= f.input :comments %>
  <%= f.label :images %>
  <br/>

  <%= f.simple_fields_for :pictures do |p| %>
    <% if p.object.id.nil? %>
      <%= p.file_field :image %>
    <% else %>
      <%= p.label 'delete' do %>
        <%= p.label :delete %>
        <%= p.check_box :image_delete %>
        <%= p.object.image_file_name %>
      <% end %>
    <% end %>
  <% end %>
  <br/>

  <%= f.button :submit %>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form' %>

<%= link_to 'Show', facility_animal_path(@facility, @animal) %> |
<%= link_to 'Back', facility_animals_path(@facility) %>

app/views/animals/index.html.erb
<div class="row">
  <h1 class="page-header">
    All Animals
    <small><%= link_to 'New Animal', new_facility_animal_path(@facility) %></small>
  </h1>
</div>

<div class="row">
  <%= render @animals %>
</div>

app/views/animals/new.html.erb
<h1>New Animal for <%= @facility.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', facility_animals_path(@facility) %>

app/views/animals/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <%= @animal.name %>
      <small> from <%= @animal.facility.name %></small>
    </h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <%= image_tag @animal.pictures.first.image.url(:portfolio_large), class: "img-responsive" if @animal.pictures.first.present? %>
    <div>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <h1> Close by Matches </h1>
    <table>
    <thead>
      <th>Name</th>
      <th>Facility Name</th>
      <th>Age</th>
      <th>Sire</th>
      <th>Dam</th>
      <th>Reproductive Status</th>
      <th>Age</th>
      <th>Facility Name</th>
    </thead>
    <tbody>
    <% @nearby_animals.each do |n| %>
      <tr age="<%=n.age%>">
      <tr>
        <td> <%= link_to n.name, animal_path(n.id)%> </td>
        <td><%=n.facility.name %></td>
        <td><%=n.age%></td>
        <td><%=n.sire %></td>
        <td><%=n.dam %></td>
        <td><%=n.reproductive_status_id %></td>
        <td><%=n.age%></td>
        <td><%=n.facility.name %></td>
      </tr>
    <% end %>
    </tbody>
    </table>
    </div>
  </div>
  <div class="col-md-4">
    <h3>Description</h3>
    <p>
      Species: <%= @animal.species.name %>
      <br/>
      Date of Birth: <%= @animal.date_of_birth %>
      <br/>
      Studbook: <%= @animal.studbook %>
      <br/>
      Sire: <%= @animal.sire %>
      <br/>
      Dam: <%= @animal.dam %>
      <br/>
      Tag: <%= @animal.tag %>
      <br/>
      Comments: <%= @animal.comments %>
      <br/>
      Searchable: <%= @animal.searchable %>
    </p>

    <h3>Actions</h3>
    <p>
      <% if current_user.try :site_admin? %>
        <%= link_to 'Edit', edit_facility_animal_path(@facility, @animal) %> |
      <% end %>
      <%= link_to 'Back', facility_animals_path(@facility) %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header">More Images</h3>
  </div>
  <% @animal.pictures.each do |p| %>
    <div class="col-sm-3 col-xs-6">
      <%= image_tag p.image.url(:portfolio_small), class: "img-responsive" %>
    </div>
  <% end %>
</div>