config/routes.rb
Rails.application.routes.draw do
  get 'search/animals'

  devise_for :users
  resources :facilities do
    resources :animals
  end
  resources :users, :only => [:index, :show]

  resources :animals, only: [:show]


  namespace :settings do
    get '/', to: 'settings#list'
    resources :species, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :sexes, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :rearings, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :reproductive_statuses, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :facility_types, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end
    resources :facility_expertises, :except => [:new, :show], :controller => 'settings' do
      put :reorder, :on => :collection
    end

  end
  

  root 'page#index'
end

app/models/animal.rb
class Animal < ApplicationRecord
  include Searchable

  Animal.search_endpoint = ENV['CLOUDSEARCH_ANIMALS_SEARCH_URL']
  Animal.doc_endpoint = ENV['CLOUDSEARCH_ANIMALS_DOC_URL']

  belongs_to :facility
  belongs_to :species
  belongs_to :sex
  belongs_to :rearing
  belongs_to :reproductive_status

  has_many :pictures, :dependent => :destroy

  validates :name, presence: true
  validates :facility_id, presence: true
  validates :species_id, presence: true
  validates :date_of_birth, presence: true

  scope :searchable, -> { where(searchable: true) }

  VALID_INTERESTS = ["keep", "sell", "trade", "loan", "sell or trade in 1-2 years", "looking for mate"].freeze
  
  before_save { |animal| animal.interests = animal.interests.uniq.select{ |e| VALID_INTERESTS.include?(e) } }

  accepts_nested_attributes_for :pictures

  def age
    return unless date_of_birth.present?
    ((Time.now - date_of_birth.to_time) / 1.year).round
  end

  def gender
    sex.try :name
  end

  VALID_INTERESTS.each do |interest|
    define_method("interest_to_#{interest}?"){ interests.include?(interest) }
  end

  private

  def ngrams
    name.split(' ').tap do |ngrams|
      ngrams << date_of_birth.year if date_of_birth.present?
      ngrams << sex.name if sex.present?
      ngrams << rearing.name if rearing.present?
      ngrams << reproductive_status.name if reproductive_status.present?
      ngrams << studbook if studbook.present?
      ngrams << tag if tag.present?
      ngrams << transponder if transponder.present?
    end
  end

  def indexed_fields
    {
      date_of_birth: date_of_birth.present? ? date_of_birth.strftime('%FT%TZ') : nil,
      species: species.name.downcase,
      facility: facility.name.downcase,
      ngrams: ngrams
    }
  end

end

app/models/animal_match.rb
class AnimalMatch < ApplicationRecord
  belongs_to :animal
  belongs_to :potential_mate
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/facility.rb
class Facility < ApplicationRecord
  has_many :animals
  has_many :facilities_users
  has_many :users, through: :facilities_users
  has_many :pictures, :dependent => :destroy
  belongs_to :facility_type
  
  accepts_nested_attributes_for :facilities_users

  validates :name, presence: true
  validates :facility_type_id, presence: true

  accepts_nested_attributes_for :pictures

  geocoded_by :address
  after_validation :geocode
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  after_validation :geocode, if: ->(facility){ facility.address.present? && facility.address_changed? }

  VALID_INTERESTS = {
    'grow_herd_size'                  => 'Interested in breeding to grow herd size',
    'maintain_herd_size'              => 'Interested in breeding to maintain herd size',
    'decrease_herd_size'              => 'Interested in decreasing herd size',
    'house_post_reproductive_animals' => 'Interested in housing post-reproductive animals',
    'house_new_species'               => 'Interested in housing new species'
  }.freeze

  before_save { |facility| facility.interests = facility.interests.uniq.select{ |e| VALID_INTERESTS.keys.include?(e) }  }

  VALID_INTERESTS.keys.each do |interest|
    define_method("interest_to_#{interest}?"){ interests.include?(interest) }
  end
end

app/models/facility_expertise.rb
class FacilityExpertise < Setting
  has_many :facilities
end

app/models/facility_type.rb
class FacilityType < Setting
  has_many :facilities
end

app/models/facility_user.rb
class FacilityUser < ApplicationRecord
  belongs_to :user
  belongs_to :facility
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :animal
  belongs_to :facility

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200>',
    medium: '300x300>',
    large:   '400x400>',
    portfolio_small: '500x300>',
    portfolio_large: '750x500>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  before_save :destroy_image?

  def image_delete
    @image_delete ||= "0"
  end

  def image_delete=(value)
    @image_delete = value
  end

  private
  def destroy_image?
    self.image.clear if image_delete == "1"
  end
end

app/models/rearing.rb
class Rearing < Setting
  has_many :animals
end

app/models/reproductive_status.rb
class ReproductiveStatus < Setting
  has_many :animals
end

app/models/setting.rb
class Setting < ApplicationRecord
  acts_as_list scope: [:type]
  
  #validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :type }
end

app/models/sex.rb
class Sex < Setting
  has_many :animals
end

app/models/species.rb
class Species < Setting
  has_many :animals
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_many :facilities_users
  has_many :facilities, through: :facilities_users

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super
    end
  end

  def full_name
    "#{first_name} #{last_name}".strip if first_name.present? || last_name.present?
  end

  def display_name
    full_name || email
  end
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    if params[:approved] == "false"
      @users = User.find_by_approved(false)
    else
      @users = User.all
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = if params[:approved] == "false"
              User.where(approved: false)
            else
              User.all
            end
  end

  def show
  end

  def not_approved
    @user_not_approved = User.find(:id)
  end

end

# This controller was added for the purpose of admin account approval

app/helpers/application_helper.rb
module ApplicationHelper

  def map_chart_styles
    {
      mapType: 'styledMap',
      showTip: true,
      useMapTypeControl: true,
      maps: {
        styledMap: {
          name: 'SPA Style',
          styles: [
            {featureType: 'poi.attraction', stylers: [{color: '#fce8b2'}]},
            {featureType: 'road.highway', stylers: [{hue: '#8c8279'}, {saturation: -50}]},
            {featureType: 'road.highway', elementType: 'labels.icon', stylers: [{hue: '#000'}, {saturation: 100}, {lightness: 50}]},
            {featureType: 'landscape', stylers: [{hue: '#74aa50'}, {saturation: 10}, {lightness: -22}]}
          ]
        }
      }
    }
  end

end

app/helpers/chart_helper.rb
module ChartHelper
	def chart(type, data, opts={})
		content_tag(:div, '',
			class: 'chart',
			id: (opts.delete(:id) || SecureRandom.uuid),
      data: {
        type: type,
        data: data.to_json,
        options: opts.to_json
      }
		).html_safe
	end
end

app/helpers/settings_helper.rb
module SettingsHelper
  def to_underscore(setting)
    setting.class.to_s.underscore.pluralize.downcase
  end
  
  def to_title(setting)
    setting.class.to_s.titleize
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ScimitarOryx</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="//www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="//www.google.com/jsapi"></script>
  </head>
  <body data-no-turbolink="true">
    <div id="main-container" class="container" style="padding:10px;">
      <nav class="navbar">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed navbar-default  text-success" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            Menu
          </button>
          <a href="<%= root_path %>" style="float:left;padding-left:15px;padding-right:15px;"><%= image_tag 'spa_logo_horizontal_pms_small.jpg', alt: "Source Population Alliance" %></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item">
              <%= link_to 'Facilities', facilities_path, class: 'nav-link' %>
            </li>
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.display_name %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to 'My Info', edit_user_registration_path %>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li>
                    <%= link_to 'Settings', settings_path %>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li>
                    <%= link_to 'Logout', destroy_user_session_path, :method => :delete%>
                  </li>
                </ul>
              </li>
            <% else %>
              <li>
                <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
              </li>
              <li>
                <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <%= render 'search/form' %>
        </div>
        <div class="row">
          <% if notice %> 
            <div class="alert alert-success alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <strong><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></strong> <%= notice %>
          </div>
        <% end %>
        <% if alert %>
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span></strong> <%= alert %>
        </div>
      <% end %>
    </nav>

    <%= yield %>
  </div>
</body>
</html>

app/views/page/index.html.erb
<div class="col-md-4 col-md-offset-4">
  
</div>